# Directories
RTL_DIR   := rtl
TEST_DIR  := test
BOARD_DIR := board_files
BUILD_DIR := build
TCL_DIR   := ../../TclScripts

SRC_DIR       := src
INC_DIR       := include
FIRMWARE_NAME := main

include ../common.mk
